<a href="https://colab.research.google.com/github/beatlesatani/coding_september/blob/main/NLP_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 38.1 MB/s eta 0:00:00


In [ ]:
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
text_test = ['nice movie indeed','I love python programing']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [ ]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'default', 'pooled_output'])

In [ ]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.81758696],
       [-0.8998871 , -0.5022245 , -0.8014913 , ..., -0.60264283,
        -0.69911593,  0.9073099 ]], dtype=float32)>

In [ ]:
bert_results['sequence_output']
print(bert_results['sequence_output']) # = 12 cause we used the BERTbase model which has 12 encoder
# this is the embedding considering the context

tf.Tensor(
[[[ 0.07292047  0.08567817  0.14476831 ... -0.09677088  0.08722127
    0.07711085]
  [ 0.1783942  -0.19006078  0.5034952  ... -0.05869824  0.32717073
   -0.15578493]
  [ 0.18701449 -0.43388748 -0.4887515  ... -0.15502778  0.00145182
   -0.24471016]
  ...
  [ 0.12083091  0.12884252  0.46453542 ...  0.0737552   0.17441946
    0.16522075]
  [ 0.07967882 -0.01190652  0.502254   ...  0.13777725  0.21002197
    0.00624588]
  [-0.07212701 -0.28303462  0.59033376 ...  0.475519    0.16668482
   -0.08920349]]

 [[ 0.04060472  0.3267152  -0.06604573 ... -0.11767717  0.20420246
    0.6038267 ]
  [ 0.42078885  0.38885787 -0.1967168  ... -0.25060505  0.2919652
    0.34592432]
  [ 1.0496671   1.0857546   0.49549276 ...  0.3162269   0.27401125
    0.26547644]
  ...
  [ 0.25059468  0.1495733   0.43479854 ...  0.21716379 -0.18325499
    0.26310873]
  [ 0.13218686  0.16939932  0.36954296 ...  0.10122065 -0.18612465
    0.23879457]
  [ 0.10344103  0.12085921  0.3779921  ...  0.14138362 -0.22387

In [ ]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']
#every value is true cause the last(12th) encoder_output after is sequence_output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

## From here move to another video and new chapter
### https://www.youtube.com/watch?v=hOCDJyZ6quA

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/beatlesatani/coding_september/main/spam.csv"
df = pd.read_csv(url,encoding="latin-1")

In [ ]:
df.shape

(5572, 5)

In [ ]:
df = df.iloc[:,:2]

In [ ]:
df=df.rename(columns={'v1': 'Category',"v2":'Message'})

In [ ]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
df_spam = df[df['Category'] == 'spam']
df_spam.shape

(747, 2)

In [ ]:
df_ham = df[df['Category'] == 'ham']
df_ham.shape

(4825, 2)

In [ ]:
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 2)

In [ ]:
df_balanced = pd.concat([df_spam,df_ham_downsampled])
df_balanced.shape

(1494, 2)

In [ ]:
df_balanced.sample(5)

Category                                            Message
2824     spam  Congratulations - Thanks to a good friend U ha...
2419     spam  SMS SERVICES For your inclusive text credits p...
582      spam  We tried to contact you re your reply to our o...
522       ham                       Were gonna go get some tacos
524      spam  URGENT!: Your Mobile No. was awarded a å£2,000...

In [ ]:
df_balanced['spam'] = df_balanced["Category"].apply(lambda x : 1 if x=='spam' else 0)

In [ ]:
df_balanced

Category                                            Message  spam
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
5        spam  FreeMsg Hey there darling it's been 3 week's n...     1
8        spam  WINNER!! As a valued network customer you have...     1
9        spam  Had your mobile 11 months or more? U R entitle...     1
11       spam  SIX chances to win CASH! From 100 to 20,000 po...     1
...       ...                                                ...   ...
2629      ham  Hey there! Glad u r better now. I hear u treat...     0
3277      ham                        What happened in interview?     0
4364      ham  Ujhhhhhhh computer shipped out with address to...     0
3939      ham                          Does daddy have a bb now.     0
2754      ham  Ok Chinese food on its way. When I get fat you...     0

[1494 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df_balanced["Message"],df_balanced['spam'],stratify=df_balanced["spam"])

In [ ]:
X_train.head(5)

65      As a valued customer, I am pleased to advise y...
516     Boltblue tones for 150p Reply POLY# or MONO# e...
4525    I want some cock! My hubby's away, I need a re...
1842                        \Are you comingdown later?\""
2379    Good evening Sir, hope you are having a nice d...
Name: Message, dtype: object

In [ ]:
bert_encoder =  hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4')
bert_preprocess= hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3')

In [ ]:
def get_sentence_embeding(sentences):
  preprocessed_text = bert_preprocess(sentences)
  return bert_encoder(preprocessed_text)['pooled_output'] #pooled_output is the 768 size vec#tor

get_sentence_embeding([
    "50$ discount. hurry up",
    'Bhavin,are you up for a volleyball game tonight?'
])

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8458222 , -0.51574653, -0.8954277 , ..., -0.7401738 ,
        -0.75189555,  0.91720545],
       [-0.81664455, -0.5138378 , -0.9361563 , ..., -0.8558676 ,
        -0.6849398 ,  0.8223354 ]], dtype=float32)>

In [ ]:
e = get_sentence_embeding([
    'banana',
    'grapes',
    'mango',
    'jeff bezos',
    'elon mask',
    'bill gates'

])

In [ ]:
e  #shape is (6,768) length of each vector is 769

<tf.Tensor: shape=(6, 768), dtype=float32, numpy=
array([[-0.760692  , -0.14219385,  0.49604586, ...,  0.42165312,
        -0.532214  ,  0.8031219 ],
       [-0.86023223, -0.2124296 ,  0.49156848, ...,  0.39797997,
        -0.60506296,  0.8447167 ],
       [-0.7128862 , -0.15463911,  0.384017  , ...,  0.3527875 ,
        -0.5099134 ,  0.734741  ],
       [-0.82533467, -0.35550597, -0.5906975 , ..., -0.01613778,
        -0.61417586,  0.8723029 ],
       [-0.89672774, -0.4204559 , -0.38606292, ..., -0.13228923,
        -0.6666911 ,  0.9103784 ],
       [-0.78544426, -0.2994976 ,  0.41027158, ...,  0.52225286,
        -0.49573594,  0.8150757 ]], dtype=float32)>

## There are two types of models you can build in tensorflow.

(1) Sequential (2) Functional

So far we have built sequential model. But below we will build functional model. More information on these two is here: https://becominghuman.ai/sequential-vs-functional-model-in-keras-20684f766057

In [ ]:
import tensorflow as tf

In [ ]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [ ]:
model.summary() #num of trainable params is769 (length of vector)

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 keras_layer_3 (KerasLayer)  {'input_type_ids': (None,    0         ['text[0][0]']                
                             128),                                                                
                              'input_word_ids': (None,                                            
                             128),                                                                
                              'input_mask': (None, 128)                                           
                             }                                                                

In [ ]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=METRICS)

In [ ]:
model.fit(X_train,y_train,epochs = 10)

Epoch 1/10
24/35 [===================>..........] - ETA: 2:41 - loss: 0.6627 - accuracy: 0.6094 - precision: 0.5949 - recall: 0.6267

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
y_predicted = model.predict(X_test)
y_predicted = y_predicted.flatten()

In [ ]:
import numpy as np

y_predicted = np.where(y_predicted > 0.5, 1, 0)
y_predicted

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_predicted)
cm

In [ ]:
from matplotlib import pyplot as plt
import seaborn as sn
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
print(classification_report(y_test, y_predicted))