<a href="https://colab.research.google.com/github/beatlesatani/coding_september/blob/main/NLP_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 20.3 MB/s eta 0:00:00


In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [8]:
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [5]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
text_test = ['nice movie indeed','I love python programing']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [9]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['encoder_outputs', 'pooled_output', 'sequence_output', 'default'])

In [10]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.81758696],
       [-0.8998871 , -0.5022245 , -0.8014913 , ..., -0.60264283,
        -0.69911593,  0.9073099 ]], dtype=float32)>

In [11]:
bert_results['sequence_output']
print(bert_results['sequence_output']) # = 12 cause we used the BERTbase model which has 12 encoder
# this is the embedding considering the context

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292047,  0.08567817,  0.14476831, ..., -0.09677088,
          0.08722127,  0.07711085],
        [ 0.1783942 , -0.19006078,  0.5034952 , ..., -0.05869824,
          0.32717073, -0.15578493],
        [ 0.18701449, -0.43388748, -0.4887515 , ..., -0.15502778,
          0.00145182, -0.24471016],
        ...,
        [ 0.12083091,  0.12884252,  0.46453542, ...,  0.0737552 ,
          0.17441946,  0.16522075],
        [ 0.07967882, -0.01190652,  0.502254  , ...,  0.13777725,
          0.21002197,  0.00624588],
        [-0.07212701, -0.28303462,  0.59033376, ...,  0.475519  ,
          0.16668482, -0.08920349]],

       [[ 0.04060472,  0.3267152 , -0.06604573, ..., -0.11767717,
          0.20420246,  0.6038267 ],
        [ 0.42078885,  0.38885787, -0.1967168 , ..., -0.25060505,
          0.2919652 ,  0.34592432],
        [ 1.0496671 ,  1.0857546 ,  0.49549276, ...,  0.3162269 ,
          0.27401125,  0.26547644],
        ...,

In [12]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']
#every value is true cause the last(12th) encoder_output after is sequence_output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

## From here move to another video and new chapter
### https://www.youtube.com/watch?v=hOCDJyZ6quA

In [23]:
import pandas as pd

In [29]:
url = "https://raw.githubusercontent.com/beatlesatani/coding_september/main/spam.csv"
df = pd.read_csv(url,encoding="latin-1")

In [32]:
df.shape

(5572, 5)

In [34]:
df = df.iloc[:,:2]

In [40]:
df=df.rename(columns={'v1': 'Category',"v2":'Message'})

In [46]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [47]:
df_spam = df[df['Category'] == 'spam']
df_spam.shape

(747, 2)

In [48]:
df_ham = df[df['Category'] == 'ham']
df_ham.shape

(4825, 2)

In [49]:
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 2)

In [50]:
df_balanced = pd.concat([df_spam,df_ham_downsampled])
df_balanced.shape

(1494, 2)

In [52]:
df_balanced.sample(5)

Category                                            Message
3427      ham  \Hi darlin did youPhone me? Im atHome if youwa...
1174      ham  Yay! You better not have told that to 5 other ...
1623      ham       Ah, well that confuses things, doesn‰Û÷t it?
4084     spam  Orange brings you ringtones from all time Char...
1327     spam  Ur balance is now å£500. Ur next question is: ...

In [55]:
df_balanced['spam'] = df_balanced["Category"].apply(lambda x : 1 if x=='spam' else 0)

In [56]:
df_balanced

Category                                            Message  spam
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
5        spam  FreeMsg Hey there darling it's been 3 week's n...     1
8        spam  WINNER!! As a valued network customer you have...     1
9        spam  Had your mobile 11 months or more? U R entitle...     1
11       spam  SIX chances to win CASH! From 100 to 20,000 po...     1
...       ...                                                ...   ...
3691      ham     No i am not having not any movies in my laptop     0
4562      ham  Come around  &lt;DECIMAL&gt; pm vikky..i'm ots...     0
1370      ham  Hope you are feeling great. Pls fill me in. Ab...     0
3138      ham                                Is ur lecture over?     0
2592      ham  My friend just got here and says he's upping h...     0

[1494 rows x 3 columns]